import type { YearTimetable } from "./timetable-types";

/**
 * ตัวอย่างข้อมูลตารางเรียนจากเอกสารจริงของสาขาวิชาศาสนาและปรัชญา (ภาคปกติ ภาษาไทย)
 * ภาคการศึกษาที่ 1 ปีการศึกษา 2569 (9 มิถุนายน 2569 - 25 กันยายน 2569)
 */
export const SAMPLE_RELIGION_PHILOSOPHY_TIMETABLE: YearTimetable[] = [
  {
    yearLevel: 1,
    semester: 1,
    academicYear: "2569",
    startDate: "9 มิถุนายน 2569",
    endDate: "25 กันยายน 2569",
    defaultRoom: "ชั้น 5 ห้อง D 516/1",
    notes: [
      "วันพระและวันนักขัตฤกษ์เป็นวันหยุดทั่วไป (ตารางเรียนวันใดตรงกับวันพระให้ยกไปเรียนวันศุกร์)",
      "เครื่องหมายดอกจัน (*) อยู่หลังชื่อรายวิชา หมายถึง ข้อสอบกลาง",
      "เครื่องหมายดอกจัน (*) อยู่หลังชื่อ หมายถึง อาจารย์ผู้รับผิดชอบรายวิชา",
      "วันพระกับวันอาทิตย์เป็นวันหยุดประจำสัปดาห์",
    ],
    slots: [
      {
        day: "Mon",
        timeRange: "09.00-11.30",
        courseCode: "000 102",
        courseName: "กฎหมายทั่วไป",
        instructors: "พระมหามงคลกานต์ ฐิตธมฺโม, รศ. ดร.* / อ.ดร.คงชิต ชินสิญจ์",
        room: "D 516/1",
        isMidtermExam: true,
      },
      {
        day: "Mon",
        timeRange: "12.30-15.10",
        courseCode: "000 136",
        courseName: "ภาษาบาลี",
        instructors: "พระครูศรีสิทธิบัณฑิต, ดร. / ผศ. ดร.บุญเกิด เจริญแนว*",
        room: "D 516/1",
      },
      {
        day: "Tue",
        timeRange: "09.00-11.30",
        courseCode: "112 305",
        courseName: "ปรัชญาอินเดียสมัยโบราณ",
        instructors: "พระจาตุรงค์ อาจารสุโภ, ผศ.ดร.* / พระมหาจรูญ กิตฺติปญฺโญ, ดร. / ผศ. ดร.ธนาธิป ฮาดเนาลี",
        room: "D 220/2",
        isMidtermExam: true,
      },
      {
        day: "Tue",
        timeRange: "12.30-15.10",
        courseCode: "000 140",
        courseName: "กรรมฐาน 1",
        instructors: "พระครูพิศิษฐ์ธรรมพิสุทธิ์, อ.ดร.* / พระมหาไพโรจน์ ญาณกุสโล, อ.ดร.",
        room: "D 516/1",
      },
      {
        day: "Tue",
        timeRange: "15.10-17.00",
        courseCode: "112 102",
        courseName: "ศาสนาพราหมณ์ - ฮินดู",
        instructors: "ผศ.ดร.คงสฤษฎ์ แพงทรัพย์* / พระครูโกวิทสุตาภรณ์, ดร.",
        room: "D 220/2",
        isMidtermExam: true,
      },
      {
        day: "Wed",
        timeRange: "09.00-11.30",
        courseCode: "999 999",
        courseName: "AI เบื้องต้น",
        instructors: "รศ.ดร.บัญญพนต์ สวัสดี / ดร.วิศาล มายัง",
        room: "D 516/1",
      },
      {
        day: "Wed",
        timeRange: "12.30-15.10",
        courseCode: "000 101",
        courseName: "มนุษย์กับสังคม",
        instructors: "พระมหาราชัน จิตฺตปาโล, ดร. / ดร.อธิเทพ ผาทา",
        room: "D 516/1",
      },
      {
        day: "Wed",
        timeRange: "15.10-17.00",
        courseCode: "SP 101",
        courseName: "บาลี 1 (รายวิชาเสริมพื้นฐาน)",
        instructors: "ผศ.ดร.บุญเกิด เจริญแนว",
        room: "D 516/1",
      },
    ],
  },
  {
    yearLevel: 2,
    semester: 1,
    academicYear: "2569",
    startDate: "9 มิถุนายน 2569",
    endDate: "25 กันยายน 2569",
    defaultRoom: "ชั้น 5 ห้อง D 516/2",
    notes: [
      "วันพระและวันนักขัตฤกษ์เป็นวันหยุดทั่วไป (ตารางเรียนวันใดตรงกับวันพระให้ยกไปเรียนวันศุกร์)",
      "เครื่องหมายดอกจัน (*) อยู่หลังชื่อรายวิชา หมายถึง ข้อสอบกลาง",
      "วันพระกับวันอาทิตย์เป็นวันหยุดประจำสัปดาห์",
    ],
    slots: [
      {
        day: "Mon",
        timeRange: "09.00-11.30",
        courseCode: "000 238",
        courseName: "เทศกาลและพิธีกรรมพระพุทธศาสนา",
        instructors: "พระครูพิศิษฐ์ธรรมพิสุทธิ์, ดร.",
        room: "D 516/2",
        isMidtermExam: true,
      },
      {
        day: "Mon",
        timeRange: "12.30-15.10",
        courseCode: "000 241",
        courseName: "กรรมฐาน 2",
        instructors: "พระครูภาวนาพัฒนบัณฑิต วิ., ผศ. ดร.* / พระภาวนาวชิรสุนทร วิ., ดร.",
        room: "D 516/2",
      },
      {
        day: "Tue",
        timeRange: "09.00-11.30",
        courseCode: "000 103",
        courseName: "คอมพิวเตอร์และเทคโนโลยีดิจิทัล",
        instructors: "พระมหายงยุทธ ธีรธมฺโม, ผศ. ดร.",
        room: "D 516/2",
        isMidtermExam: true,
      },
      {
        day: "Tue",
        timeRange: "12.30-15.10",
        courseCode: "000 116",
        courseName: "ภาษาสันสกฤตเบื้องต้น",
        instructors: "อ.ดร.สุดาพร เขียวงามดี",
        room: "D 516/2",
      },
      {
        day: "Wed",
        timeRange: "09.00-11.30",
        courseCode: "000 233",
        courseName: "ศาสนาทั่วไป",
        instructors: "ผศ.ดร.แสวง นิลนามะ* / ผศ.ดร.คงสฤษฎ์ แพงทรัพย์",
        room: "D 516/2",
      },
      {
        day: "Wed",
        timeRange: "12.30-15.10",
        courseCode: "112 412",
        courseName: "พุทธปรัชญา",
        instructors: "พระมหามงคลกานต์ ฐิตธมฺโม, รศ. ดร.* / ดร.ไชยา เสนแสนยา",
        room: "D 220/2",
      },
      {
        day: "Wed",
        timeRange: "15.10-17.00",
        courseCode: "888 888",
        courseName: "Gamification",
        instructors: "รศ.ดร.วิลาวัลย์ / รศ.ดร.วราพร",
        room: "D 516/2",
      },
      {
        day: "Thu",
        timeRange: "09.00-11.30",
        courseCode: "SP 103",
        courseName: "บาลี 3 (รายวิชาเสริมพื้นฐาน)",
        instructors: "ผศ.ดร.บุญเกิด เจริญแนว",
        room: "D 516/2",
      },
    ],
  },
];

/**
 * ตัวอย่างข้อมูลตารางเรียนจากเอกสารจริงของ Buddhist Studies (English Program)
 * First Semester, Academic Year 2026 (June 9, 2026 – September 25, 2026)
 */
export const SAMPLE_BUDDHIST_STUDIES_EN_TIMETABLE: YearTimetable[] = [
  {
    yearLevel: 1,
    semester: 1,
    academicYear: "2026",
    startDate: "June 9, 2026",
    endDate: "September 25, 2026",
    defaultRoom: "Room No. D 517-518",
    notes: [
      "The class day is Buddhist Holy Day (Dhammasavana Day), it is replaced on Friday.",
      "The Buddhist Holy Days and Sundays are weekly holiday.",
      "Official Days are Holiday.",
      "This schedule will be changed properly.",
    ],
    slots: [
      {
        day: "Mon",
        timeRange: "09.00-11.30",
        courseCode: "101 101",
        courseName: "Buddhism and Science",
        instructors: "Dr. Onjira Wongsapan",
        room: "D 517-518",
      },
      {
        day: "Mon",
        timeRange: "13.00-15.30",
        courseCode: "101 103",
        courseName: "Communication in Tipitaka",
        instructors: "Asst. Prof. Phramaha Yongyut Dhiradhammo, Ph.D. / Ven. Thit Zana",
        room: "D 517-518",
      },
      {
        day: "Tue",
        timeRange: "09.00-11.30",
        courseCode: "000 102",
        courseName: "General Law",
        instructors: "Asst. Prof. Dr. Doungkamon Tongkanaraksa",
        room: "D 517-518",
      },
      {
        day: "Tue",
        timeRange: "13.00-15.30",
        courseCode: "000 136",
        courseName: "Pali",
        instructors: "Assoc. Prof. Phra Dhammavajirapanyacarya, Ph.D. / Assoc. Prof. W. Piyaratana, Ph.D.",
        room: "D 517-518",
      },
      {
        day: "Tue",
        timeRange: "15.30-17.00",
        courseCode: "OSP 101",
        courseName: "Pali",
        instructors: "Asst. Prof. Piphat Khongprasert",
        room: "D 517-518",
      },
      {
        day: "Wed",
        timeRange: "09.00-11.30",
        courseCode: "000 101",
        courseName: "Man and Society",
        instructors: "Ven. Dharma Priya Bhikkhu, Ph.D.",
        room: "D 517-518",
      },
      {
        day: "Wed",
        timeRange: "13.00-15.30",
        courseCode: "000 140",
        courseName: "Buddhist Meditation I",
        instructors: "Phra Sukheesom Silatechaputtiyo, Ph.D.",
        room: "D 517-518",
      },
    ],
  },
  {
    yearLevel: 2,
    semester: 1,
    academicYear: "2026",
    startDate: "June 9, 2026",
    endDate: "September 25, 2026",
    defaultRoom: "Room No. D 519-520",
    notes: [
      "The class day is Buddhist Holy Day (Dhammasavana Day), it is replaced on Friday.",
      "The Buddhist Holy Days and Sundays are weekly holiday.",
      "Official Days are Holiday.",
    ],
    slots: [
      {
        day: "Mon",
        timeRange: "09.00-11.30",
        courseCode: "000 116",
        courseName: "Basic Sanskrit",
        instructors: "Asst. Prof. W. Piyaratana, Ph.D. / Dr. Sudaporn Kiewngamdee",
        room: "D 519-520",
      },
      {
        day: "Mon",
        timeRange: "13.00-15.30",
        courseCode: "000 238",
        courseName: "Buddhist Festival and Traditions",
        instructors: "Asst. Prof. Dr. Supapan Permpool",
        room: "D 519-520",
      },
      {
        day: "Tue",
        timeRange: "09.00-11.30",
        courseCode: "000 233",
        courseName: "General Religions",
        instructors: "Asst. Prof. Dr. Dhanardhip Hardnualee",
        room: "D 519-520",
      },
      {
        day: "Tue",
        timeRange: "13.00-15.30",
        courseCode: "000 103",
        courseName: "Computer and Digital Technology",
        instructors: "Asst. Prof. Phramaha Yongyut Dhiradhammo, Ph.D.",
        room: "D 519-520",
      },
      {
        day: "Wed",
        timeRange: "09.00-11.30",
        courseCode: "000 241",
        courseName: "Buddhist Meditation II",
        instructors: "Phra Sukheesom Silatechaputtiyo, Ph.D. / Ven. Dr. Subinoy Bhikku*",
        room: "D 519-520",
      },
      {
        day: "Wed",
        timeRange: "13.00-15.30",
        courseCode: "101 205",
        courseName: "Buddhism and Ecology",
        instructors: "Dr. Nadnapang Phophichit",
        room: "D 519-520",
      },
      {
        day: "Thu",
        timeRange: "09.00-11.30",
        courseCode: "OSP 103",
        courseName: "Pali",
        instructors: "Asst. Prof. Piphat Khongprasert / Phramaha Niran Kalyanamedhi, Ph.D.*",
        room: "D 519-520",
      },
      {
        day: "Thu",
        timeRange: "13.00-15.30",
        courseCode: "HOME",
        courseName: "Library Resource / Home Room",
        instructors: "Advisor / Faculty Staff",
        room: "D 519-520",
      },
    ],
  },
  {
    yearLevel: 3,
    semester: 1,
    academicYear: "2026",
    startDate: "June 9, 2026",
    endDate: "September 25, 2026",
    defaultRoom: "Room No. D 123",
    notes: [
      "The class day is Buddhist Holy Day (Dhammasavana Day), it is replaced on Friday.",
      "The Buddhist Holy Days and Sundays are weekly holiday.",
      "Official Days are Holiday.",
    ],
    slots: [
      {
        day: "Mon",
        timeRange: "09.00-11.30",
        courseCode: "101 322",
        courseName: "Political Science in Tipitaka",
        instructors: "Phramaha Jaroon Kittiyanno, Ph.D.",
        room: "D 123",
      },
      {
        day: "Mon",
        timeRange: "13.00-15.30",
        courseCode: "000 342",
        courseName: "Buddhist Meditation III",
        instructors: "Phra Sukheesom Silatechaputtiyo, Ph.D.",
        room: "D 123",
      },
      {
        day: "Tue",
        timeRange: "09.00-11.30",
        courseCode: "101 314",
        courseName: "Visuddhimagga Studies",
        instructors: "Assoc. Prof. Phra Dhammavajirapanyacarya, Ph.D. / Assoc. Prof. W. Piyaratana, Ph.D.",
        room: "D 123",
      },
      {
        day: "Tue",
        timeRange: "13.00-15.30",
        courseCode: "101 307",
        courseName: "Theravada Buddhist Philosophy",
        instructors: "Asst. Prof. Dr. Dhanardhip Hardnualee",
        room: "D 123",
      },
      {
        day: "Wed",
        timeRange: "09.00-11.30",
        courseCode: "101 308",
        courseName: "Buddhism and Human Rights",
        instructors: "Dr. Tratep Techapornchai",
        room: "D 123",
      },
      {
        day: "Wed",
        timeRange: "13.00-15.30",
        courseCode: "101 322",
        courseName: "Comparison Between Theravada and Mahayana",
        instructors: "Phra Kriengsak Sirisakko, Ph.D. / Dr. Low Yuen Fah*",
        room: "D 123",
      },
    ],
  },
  {
    yearLevel: 4,
    semester: 1,
    academicYear: "2026",
    startDate: "June 9, 2026",
    endDate: "September 25, 2026",
    defaultRoom: "Room No. D 124",
    notes: [
      "The class day is Buddhist Holy Day (Dhammasavana Day), it is replaced on Friday.",
      "The Buddhist Holy Days and Sundays are weekly holiday.",
      "Official Days are Holiday.",
    ],
    slots: [
      {
        day: "Mon",
        timeRange: "09.00-11.30",
        courseCode: "101 415",
        courseName: "Jataka Studies",
        instructors: "Phramaha Rachan Cittapalo, Ph.D.",
        room: "D 124",
      },
      {
        day: "Mon",
        timeRange: "13.00-15.30",
        courseCode: "101 326",
        courseName: "Buddhism and Peace",
        instructors: "Dr. Onjira Wongsaparn",
        room: "D 124",
      },
      {
        day: "Tue",
        timeRange: "09.00-11.30",
        courseCode: "101 418",
        courseName: "English for Buddhism",
        instructors: "Assoc. Prof. Dr. Jutamas Vareesengthip",
        room: "D 124",
      },
      {
        day: "Tue",
        timeRange: "13.00-15.30",
        courseCode: "000 443",
        courseName: "Buddhist Meditation IV",
        instructors: "Phra Sukheesom Silatechaputtiyo, Ph.D.",
        room: "D 124",
      },
      {
        day: "Wed",
        timeRange: "09.00-11.30",
        courseCode: "101 431",
        courseName: "Buddhism and Modern Economy",
        instructors: "Asst. Prof. Dr. Soontaraporn Techapalokul",
        room: "D 124",
      },
      {
        day: "Wed",
        timeRange: "13.00-15.30",
        courseCode: "000 416",
        courseName: "Mahayana Buddhism",
        instructors: "Assoc. Prof. Ven. Piyaratana, Ph.D.",
        room: "D 124",
      },
    ],
  },
];
